# Generated by Django 5.1.1 on 2024-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.CharField(max_length=50),
        ),
    ]
