# Generated by Django 5.1.1 on 2024-09-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_station_lang_alter_station_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='english_title',
            new_name='English_title',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='lang',
            new_name='Lang',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='lat',
            new_name='Lat',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='line',
            new_name='Line',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='title',
            new_name='Title',
        ),
    ]
